apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
     grafana_datasource: "1"
  namespace: observability
data:
  datasource.yaml: |-
     apiVersion: 1
     datasources:
       - name: Loki
         type: loki
         url: "http://loki-loki-distributed-query-frontend:3100"